name: android-ci

on:
  push:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    working-directory: bitacora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.x"
          channel: "stable"
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Format check
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze

      - name: Decode keystore
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        run: echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > $HOME/upload.jks
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Build AAB (release)
        env:
          UPLOAD_STORE_FILE: $HOME/upload.jks
          UPLOAD_STORE_PASSWORD: ${{ secrets.UPLOAD_STORE_PASSWORD }}
          UPLOAD_KEY_ALIAS: ${{ secrets.UPLOAD_KEY_ALIAS }}
          UPLOAD_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
        run: flutter build appbundle --release

      - name: Build APKs (opcionales)
        if: ${{ always() }}
        run: flutter build apk --release --split-per-abi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: |
            bitacora/build/app/outputs/bundle/release/*.aab
            bitacora/build/app/outputs/flutter-apk/*-release.apk
            bitacora/build/app/outputs/mapping/release/mapping.txt

  deploy-internal:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: android-builds
          path: dist

      - name: Upload to Play (internal)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlain: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{ secrets.PLAY_PACKAGE_NAME }}
          releaseFiles: dist/*.aab
          track: internal
          status: completed
          mappingFile: dist/mapping.txt