name: CI
on:
  push:
    branches: [main, master]
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - name: Pub get
        run: flutter pub get
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze (fatal infos & warnings)
        run: dart analyze --fatal-infos --fatal-warnings
      - name: Run tests with coverage
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed=random
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov.info
      - name: Run integration tests (host)
        run: flutter test integration_test
      - name: Build Android APK (Debug)
        run: flutter build apk --debug
